# Generated by Django 4.2.1 on 2023-06-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='technique',
            name='categories',
            field=models.ManyToManyField(related_name='techniques', to='muaythaiapp.category'),
        ),
    ]
