# Generated by Django 4.2.1 on 2023-06-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0002_category_technique_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='techniques',
            field=models.ManyToManyField(related_name='related_categories', to='muaythaiapp.technique'),
        ),
        migrations.AddField(
            model_name='technique',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='technique_images/'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='categories',
            field=models.ManyToManyField(related_name='related_techniques', to='muaythaiapp.category'),
        ),
    ]
