# Generated by Django 4.2.1 on 2023-06-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0003_category_techniques_technique_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
