# Generated by Django 4.2.1 on 2023-06-07 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0004_alter_technique_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='technique',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='trainingdrill',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='trainingdrill',
            name='updated_at',
        ),
    ]
