# Generated by Django 4.2.1 on 2023-06-09 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0005_remove_technique_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingdrill',
            options={'ordering': ['sequence']},
        ),
        migrations.AddField(
            model_name='trainingdrill',
            name='parent_drill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_drills', to='muaythaiapp.trainingdrill'),
        ),
        migrations.AddField(
            model_name='trainingdrill',
            name='sequence',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
