# Generated by Django 4.2.1 on 2023-06-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0007_alter_technique_description_alter_technique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
        migrations.AlterField(
            model_name='technique',
            name='name',
            field=models.CharField(default='Untitled', max_length=100),
        ),
    ]
