# Generated by Django 4.2.1 on 2023-06-23 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0008_alter_technique_description_alter_technique_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
