# Generated by Django 4.2.1 on 2023-06-23 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0009_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(default='No description provided'),
        ),
    ]
