# Generated by Django 4.2.1 on 2023-06-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0010_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technique',
            name='categories',
            field=models.ManyToManyField(blank=True, to='muaythaiapp.technique'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
