# Generated by Django 4.2.1 on 2023-06-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaythaiapp', '0011_alter_technique_categories_delete_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technique',
            name='categories',
        ),
        migrations.AddField(
            model_name='technique',
            name='category',
            field=models.CharField(default='Default Category', max_length=100),
        ),
    ]
